/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Librarybook.ui;

import com.Librarybook.DAO.PhieuMuonCTDAO;
import com.Librarybook.DAO.PhieuMuonDAO;
import com.Librarybook.DAO.SachDAO;
import com.Librarybook.DAO.TheLoaiDAO;
import com.Librarybook.entity.Sach;
import com.Librarybook.utils.Auth;
import com.Librarybook.utils.MsgBox;
import com.Librarybook.utils.Ximage;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import com.Librarybook.ui.ManHinhChaoJDialog;
import com.Librarybook.ui.DoiMatKhauJDialog;
import com.Librarybook.ui.DangnhapJDalog;
import com.Librarybook.ui.NXBJDialog;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author my
 */
public class ManHinhChinhJDalog extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChinh
     */
    public ManHinhChinhJDalog() {
        initComponents();
        init();
        tblsach.setDefaultEditor(Object.class, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsach = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbomatacgia = new javax.swing.JComboBox<>();
        cbomanxb = new javax.swing.JComboBox<>();
        lbldanhsach = new javax.swing.JScrollPane();
        tbltracucsach = new javax.swing.JTable();
        btndanhsach = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbldongho = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnhethong = new javax.swing.JMenu();
        mnidangnhap = new javax.swing.JMenuItem();
        mnidangxuat = new javax.swing.JMenuItem();
        mnidoimatkhau = new javax.swing.JMenuItem();
        mniketthuc = new javax.swing.JMenuItem();
        jmnquanly = new javax.swing.JMenu();
        mninhanvien = new javax.swing.JMenuItem();
        mnisach = new javax.swing.JMenuItem();
        mninguoimuon = new javax.swing.JMenuItem();
        mnitheloai = new javax.swing.JMenuItem();
        mniphieumuon = new javax.swing.JMenuItem();
        mnitacgia = new javax.swing.JMenuItem();
        mninxb = new javax.swing.JMenuItem();
        jmnthongke = new javax.swing.JMenu();
        mnisonguoimuon = new javax.swing.JMenuItem();
        mnisonguoidoc = new javax.swing.JMenuItem();
        mnidanhsachmuon = new javax.swing.JMenuItem();
        jmnhotro = new javax.swing.JMenu();
        mnituvan = new javax.swing.JMenuItem();
        mnigiaidap = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FPoly_ManHinhChinh");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 4, 2, new java.awt.Color(0, 153, 153)));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/library3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trang chủ", new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/tutorial.png")), jPanel2); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 4, 2, new java.awt.Color(0, 153, 153)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/tutorial (1).png"))); // NOI18N
        jLabel6.setText("Sách");

        tblsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Mã thể loại", "Tác giả", "NXB", "Số lượng", "Nội dung"
            }
        ));
        jScrollPane1.setViewportView(tblsach);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sách ", new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/books.png")), jPanel3); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 4, 2, new java.awt.Color(0, 153, 153)));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        jLabel7.setText("Tìm kiếm theo tác giả ");

        jLabel8.setText("Tìm kiếm theo NXB ");

        cbomatacgia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã tác gải ", " ", " " }));
        cbomatacgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbomatacgiaActionPerformed(evt);
            }
        });

        cbomanxb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã NXB", " ", " ", " " }));
        cbomanxb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbomanxbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cbomatacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cbomanxb, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(cbomatacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbomanxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbltracucsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "NXB", "Tên tác giả", "Thể loại"
            }
        ));
        lbldanhsach.setViewportView(tbltracucsach);

        btndanhsach.setBackground(new java.awt.Color(204, 204, 255));
        btndanhsach.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndanhsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/book (1).png"))); // NOI18N
        btndanhsach.setText("Chi tiết sách ");
        btndanhsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndanhsachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbldanhsach)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndanhsach)
                .addGap(60, 60, 60))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndanhsach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Tra cứu sách ", new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/research.png")), jPanel4); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("LibraryBooks");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/favpng_fpt-polytechnic-logo-image-symbol2.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Trường Cao Đẳng FPT Polytechnic - Cơ Sở 3");

        lbldongho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldongho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/alarm-clock.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/1584328561_Hi.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Hệ thống quản lý thư viện ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(558, 558, 558)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setAlignmentY(0.5F);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jmnhethong.setText("Hệ thống");
        jmnhethong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnidangnhap.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mnidangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/icons8-home-24.png"))); // NOI18N
        mnidangnhap.setText("Đăng nhập");
        mnidangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangnhapActionPerformed(evt);
            }
        });
        jmnhethong.add(mnidangnhap);

        mnidangxuat.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mnidangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/logout.png"))); // NOI18N
        mnidangxuat.setText("Đăng xuất");
        mnidangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangxuatActionPerformed(evt);
            }
        });
        jmnhethong.add(mnidangxuat);

        mnidoimatkhau.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mnidoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/refresh.png"))); // NOI18N
        mnidoimatkhau.setText("Đổi mật khẩu");
        mnidoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidoimatkhauActionPerformed(evt);
            }
        });
        jmnhethong.add(mnidoimatkhau);

        mniketthuc.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mniketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/ending.png"))); // NOI18N
        mniketthuc.setText("Kết thúc");
        mniketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniketthucActionPerformed(evt);
            }
        });
        jmnhethong.add(mniketthuc);

        jMenuBar1.add(jmnhethong);

        jmnquanly.setText("Quản lý");
        jmnquanly.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mninhanvien.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mninhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/employee.png"))); // NOI18N
        mninhanvien.setText("Nhân Viên");
        mninhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninhanvienActionPerformed(evt);
            }
        });
        jmnquanly.add(mninhanvien);

        mnisach.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mnisach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/book.png"))); // NOI18N
        mnisach.setText("Sách");
        mnisach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnisachActionPerformed(evt);
            }
        });
        jmnquanly.add(mnisach);

        mninguoimuon.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mninguoimuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/student-with-graduation-cap.png"))); // NOI18N
        mninguoimuon.setText("Người mượn");
        mninguoimuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninguoimuonActionPerformed(evt);
            }
        });
        jmnquanly.add(mninguoimuon);

        mnitheloai.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mnitheloai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/publisher.png"))); // NOI18N
        mnitheloai.setText("Thể loại");
        mnitheloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitheloaiActionPerformed(evt);
            }
        });
        jmnquanly.add(mnitheloai);

        mniphieumuon.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mniphieumuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/poem.png"))); // NOI18N
        mniphieumuon.setText("Phiếu mượn ");
        mniphieumuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniphieumuonActionPerformed(evt);
            }
        });
        jmnquanly.add(mniphieumuon);

        mnitacgia.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mnitacgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/businessman.png"))); // NOI18N
        mnitacgia.setText("Tác giả");
        mnitacgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitacgiaActionPerformed(evt);
            }
        });
        jmnquanly.add(mnitacgia);

        mninxb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mninxb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/businessman.png"))); // NOI18N
        mninxb.setText("Nhà xuất bản ");
        mninxb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninxbActionPerformed(evt);
            }
        });
        jmnquanly.add(mninxb);

        jMenuBar1.add(jmnquanly);

        jmnthongke.setText("Thống kê");
        jmnthongke.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jmnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnthongkeActionPerformed(evt);
            }
        });

        mnisonguoimuon.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mnisonguoimuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/Clien list.png"))); // NOI18N
        mnisonguoimuon.setText("Số người đọc");
        mnisonguoimuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnisonguoimuonActionPerformed(evt);
            }
        });
        jmnthongke.add(mnisonguoimuon);

        mnisonguoidoc.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mnisonguoidoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/User group.png"))); // NOI18N
        mnisonguoidoc.setText("Thống kê sách");
        mnisonguoidoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnisonguoidocActionPerformed(evt);
            }
        });
        jmnthongke.add(mnisonguoidoc);

        mnidanhsachmuon.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mnidanhsachmuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/book (1).png"))); // NOI18N
        mnidanhsachmuon.setText("Thống kê tiền phạt ");
        mnidanhsachmuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidanhsachmuonActionPerformed(evt);
            }
        });
        jmnthongke.add(mnidanhsachmuon);

        jMenuBar1.add(jmnthongke);

        jmnhotro.setText("Hỗ trợ");
        jmnhotro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnituvan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mnituvan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/customer-support.png"))); // NOI18N
        mnituvan.setText("Tư vấn ");
        mnituvan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnituvanActionPerformed(evt);
            }
        });
        jmnhotro.add(mnituvan);

        mnigiaidap.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mnigiaidap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Librarybook/icon/consultant-services.png"))); // NOI18N
        mnigiaidap.setText("Giải đáp thắc mắc");
        mnigiaidap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnigiaidapActionPerformed(evt);
            }
        });
        jmnhotro.add(mnigiaidap);

        jMenuBar1.add(jmnhotro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnidangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangxuatActionPerformed
        // TODO add your handling code here:
        DangXuat();
    }//GEN-LAST:event_mnidangxuatActionPerformed

    private void mnisonguoimuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnisonguoimuonActionPerformed
        // TODO add your handling code here:
        OpenThongKe(0);

    }//GEN-LAST:event_mnisonguoimuonActionPerformed

    private void mnidanhsachmuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidanhsachmuonActionPerformed
        // TODO add your handling code here:
        OpenThongKe(2);
    }//GEN-LAST:event_mnidanhsachmuonActionPerformed

    private void mnidangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangnhapActionPerformed
        // TODO add your handling code here:
        DangNhap();
    }//GEN-LAST:event_mnidangnhapActionPerformed

    private void mnidoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidoimatkhauActionPerformed
        // TODO add your handling code here:
        openDoiMatKhau();
    }//GEN-LAST:event_mnidoimatkhauActionPerformed

    private void mniketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniketthucActionPerformed
        // TODO add your handling code here:
        KetThuc();
    }//GEN-LAST:event_mniketthucActionPerformed

    private void mninhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninhanvienActionPerformed
        // TODO add your handling code here:
        OpenNhanVien();
    }//GEN-LAST:event_mninhanvienActionPerformed

    private void mnisachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnisachActionPerformed
        // TODO add your handling code here:
        OpenSach();
    }//GEN-LAST:event_mnisachActionPerformed

    private void mnitacgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitacgiaActionPerformed
        // TODO add your handling code here:
        OpenTacGia();
    }//GEN-LAST:event_mnitacgiaActionPerformed

    private void mninxbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninxbActionPerformed
        // TODO add your handling code here:
        OpenNXB();
    }//GEN-LAST:event_mninxbActionPerformed

    private void mnitheloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitheloaiActionPerformed
        // TODO add your handling code here:
        OpenTheLoaiSach();
    }//GEN-LAST:event_mnitheloaiActionPerformed

    private void mninguoimuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninguoimuonActionPerformed
        // TODO add your handling code here:
        openNguoiMuon();

    }//GEN-LAST:event_mninguoimuonActionPerformed

    private void mniphieumuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniphieumuonActionPerformed
        // TODO add your handling code here:
        OpenPhieuMuon();
    }//GEN-LAST:event_mniphieumuonActionPerformed

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:
        this.fillTableTraCuuSach();

    }//GEN-LAST:event_txttimkiemActionPerformed

    private void cbomatacgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbomatacgiaActionPerformed
        // TODO add your handling code here:
        this.fillTableTraCuuSach();
    }//GEN-LAST:event_cbomatacgiaActionPerformed

    private void cbomanxbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbomanxbActionPerformed
        // TODO add your handling code here:
        this.fillTableTraCuuSach();
    }//GEN-LAST:event_cbomanxbActionPerformed

    private void btndanhsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndanhsachActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int row = tbltracucsach.getSelectedRow();
        if (row == -1) {
            MsgBox.alert(this, "Chọn Một Cuốn Sách Để Xem!");
        } else {
            String maSachChon = String.valueOf(tbltracucsach.getValueAt(row, 0));
            Sach sachChon = new Sach();
            sachChon = sdao.selectById(maSachChon);
            new ChiTietSachJDalog(this, true, sachChon).setVisible(true);
        }
    }//GEN-LAST:event_btndanhsachActionPerformed

    private void jmnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnthongkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnthongkeActionPerformed

    private void mnisonguoidocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnisonguoidocActionPerformed
        // TODO add your handling code here:
        OpenThongKe(1);
    }//GEN-LAST:event_mnisonguoidocActionPerformed

    private void mnituvanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnituvanActionPerformed
        // TODO add your handling code here:
        OpenHoTro(0);
    }//GEN-LAST:event_mnituvanActionPerformed

    private void mnigiaidapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnigiaidapActionPerformed
        // TODO add your handling code here:
        OpenHoTro(1);
    }//GEN-LAST:event_mnigiaidapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJDalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJDalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJDalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJDalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhChinhJDalog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndanhsach;
    private javax.swing.JComboBox<String> cbomanxb;
    private javax.swing.JComboBox<String> cbomatacgia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu jmnhethong;
    private javax.swing.JMenu jmnhotro;
    private javax.swing.JMenu jmnquanly;
    private javax.swing.JMenu jmnthongke;
    private javax.swing.JScrollPane lbldanhsach;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JMenuItem mnidangnhap;
    private javax.swing.JMenuItem mnidangxuat;
    private javax.swing.JMenuItem mnidanhsachmuon;
    private javax.swing.JMenuItem mnidoimatkhau;
    private javax.swing.JMenuItem mnigiaidap;
    private javax.swing.JMenuItem mniketthuc;
    private javax.swing.JMenuItem mninguoimuon;
    private javax.swing.JMenuItem mninhanvien;
    private javax.swing.JMenuItem mninxb;
    private javax.swing.JMenuItem mniphieumuon;
    private javax.swing.JMenuItem mnisach;
    private javax.swing.JMenuItem mnisonguoidoc;
    private javax.swing.JMenuItem mnisonguoimuon;
    private javax.swing.JMenuItem mnitacgia;
    private javax.swing.JMenuItem mnitheloai;
    private javax.swing.JMenuItem mnituvan;
    private javax.swing.JTable tblsach;
    private javax.swing.JTable tbltracucsach;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
    SachDAO sdao = new SachDAO();
    TheLoaiDAO tldao = new TheLoaiDAO();
    PhieuMuonDAO pmdao = new PhieuMuonDAO();
    PhieuMuonCTDAO ctpmdao = new PhieuMuonCTDAO();

    private void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(Ximage.getAppIcon());

        new ManHinhChaoJDialog(this, true).setVisible(true);
        new DangnhapJDalog(this, true).setVisible(true);
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                String text = formater.format(now);
                lbldongho.setText(text);
            }
        }).start();
        this.fillComboboxNXB();
        this.fillComboboxTG();
        this.fillTableSach();
    }

    void openDoiMatKhau() {
        if (Auth.isLogin()) {
            new DoiMatKhauJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }
    void openNguoiMuon() {
        if (Auth.isLogin()) {
            new NguoiMuonJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void DangXuat() {
        Auth.clear();
        new DangnhapJDalog(this, true).setVisible(true);
    }

    void DangNhap() {
        new DangnhapJDalog(this, true).setVisible(true);
    }

    void KetThuc() {
        if (MsgBox.confirm(this, "Bạn Có Muốn Kết Thúc Làm Việc ?")) {
            System.exit(0);
        }
    }

    void OpenNhanVien() {
        if (Auth.isLogin()) {
            new NhanVienJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void OpenHoTro(int index) {
        if (Auth.isLogin()) {
            if (index == 2 && !Auth.isManager()) {
                MsgBox.alert(this, "Bạn Không Có Quyền Xem THông Tin Doanh Thu!");
                return;
            }
            HoTroJDialog tkwin = new HoTroJDialog(this, true, index);
            tkwin.setVisible(true);
            tkwin.selectTab(index);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void OpenTacGia() {
        if (Auth.isLogin()) {
            new TacGiaJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void OpenNXB() {
        if (Auth.isLogin()) {
            new NXBJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void OpenSach() {
        if (Auth.isLogin()) {
            new QuanLySachJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void OpenTheLoaiSach() {
        if (Auth.isLogin()) {
            new TheLoaiSachJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void OpenPhieuMuon() {
        if (Auth.isLogin()) {
            new PhieuMuonJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void OpenThongKe(int index) {
        if (Auth.isLogin()) {
            if (index == 3 && !Auth.isManager()) {
                MsgBox.alert(this, "Bạn Không Có Quyền Xem THông Tin Doanh Thu!");
                return;
            }
            ThongKeJDialog tkwin = new ThongKeJDialog(this, true, index);
            tkwin.setVisible(true);
            tkwin.selectTab(index);
        } else {
            MsgBox.alert(this, "Vui Lòng Đăng Nhập!");
        }
    }

    void fillTableSach() {
        DefaultTableModel model = (DefaultTableModel) tblsach.getModel();
        model.setRowCount(0);
        try {
            List<Sach> list = sdao.selectAll();
            for (Sach s : list) {
                Object[] row = {
                    s.getMaSach(),
                    s.getTenSach(),
                    s.getMaTheLoai(),
                    s.getTenTacGia(),
                    s.getTenNXB(),
                    s.getSoLuong(),
                    s.getTomTatND()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Truy Vấn Dữ Liệu !");
        }
        fillTableTraCuuSach();
    }

    void fillTableTraCuuSach() {

        DefaultTableModel model = (DefaultTableModel) tbltracucsach.getModel();
        model.setRowCount(0);
        try {
            String keywork = txttimkiem.getText();

            String nxb = (String) cbomanxb.getSelectedItem();
            String tacGia = (String) cbomatacgia.getSelectedItem();
            List<Sach> list = sdao.selectAll();
            for (Sach s : list) {
                Object[] row = {
                    s.getMaSach(),
                    s.getTenSach(),
                    s.getTenTacGia(),
                    s.getTenNXB(),
                    s.getMaTheLoai()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Truy Vấn Dữ Liệu !");
        }
//        fillComboboxDanhMuc();
    }

    void fillComboboxNXB() {

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost;database=QLThuVien";
            Connection con = DriverManager.getConnection(url, "sa", "");
            Statement st = con.createStatement();
            String sql = "Select MaNXB from NhaXuatBan";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                cbomanxb.addItem(rs.getString("MaNXB"));
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Truy vấn vào ComboBoxDM!");
        }

    }

    void fillComboboxTG() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost;database=QLThuVien";
            Connection con = DriverManager.getConnection(url, "sa", "");
            Statement st = con.createStatement();
            String sql = "Select MaTacGia from TacGia";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                cbomatacgia.addItem(rs.getString("MaTacGia"));
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Truy vấn vào ComboBoxTL!");
        }
    }

}
